name: ssh
# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Run tests"]
    types:
      - completed
jobs: 
  ssh:
    runs-on: ubuntu-20.04 
    steps:
    -name:  connect
      run:  echo "Hello, world!"
