name: Run tests

# Run this workflow whenever something new is pushed.
on: push
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        # Specify some input for this particular action
        with:
          python-version: '3.8.6'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
  connect:
    needs: run-tests
    runs-on: ubuntu-20.04
    steps:  
      - name: login-server
        uses: appleboy/ssh-action@master
        with :
          host : ${{secrets.SSH_HOST}}
          username : root
          port : 22
          key : ${{secrets.DIGITAL_OCEAN}}
          script : |
            cd ../home/
            rm -r flask-site
            git clone https://github.com/arifn1988/flask-site 
            systemctl restart farm
