name: Run tests

# Run this workflow whenever something new is pushed.
on: push
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        # Specify some input for this particular action
        with:
          python-version: '3.8.6'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
  connect:
    runs-on: ubuntu-20.04
    needs: run-tests
    steps:
      - name: ssh-key
        uses: shimataro/ssh-key-action@v2
        with: 
          key: ${{secrets.DIGITAL_OCEAN}}
          known_hosts: 'Just a placeholder to avoid errors'
      - name: known-hosts
        run: ssh-keyscan -H ${{secrets.SSH_HOST}} >> ~/.ssh/known_hosts
      - name: upload-website
        run: rsync -avz ./dist/ root@${{secrets.SSH_HOST}}:/home/
